# -*- coding: utf-8 -*-
from pathlib import Path
path = Path('Makhzan/app.py')
text = path.read_text(encoding='utf-8')
start = text.index("return render_template('sales/add.html', form=form, products=products, inventories=inventories)") + len("return render_template('sales/add.html', form=form, products=products, inventories=inventories)")
end = text.index("@app.route('/sales/view', methods=['GET'])", start)
block = """\n\n@app.route('/cashier/pos')\n@login_required\n@cashier_required\ndef cashier_pos():\n    form = SaleForm()\n    customers = Customer.query.all()\n    form.customer_id.choices = [(0, '-- Select Customer --')] + [(c.id, c.name) for c in customers]\n    products = Product.query.all()\n    inventories = {inv.product_id: inv.quantity for inv in Inventory.query.all()}\n    if not form.invoice_number.data:\n        form.invoice_number.data = generate_invoice_number()\n    form.sale_date.data = form.sale_date.data or datetime.now().date()\n    form.payment_method.data = form.payment_method.data or 'cash'\n    return render_template('cashier/pos.html', form=form, products=products, inventories=inventories)\n\n@app.route('/cashier/product-info')\n@login_required\n@cashier_required\ndef cashier_product_info():\n    code = (request.args.get('code') or '').strip()\n    if not code:\n        return jsonify({'error': 'Code missing.'}), 400\n    product = None\n    if code.isdigit():\n        product = Product.query.filter_by(id=int(code)).first()\n    if not product:\n        product = Product.query.filter((Product.barcode == code) | (Product.sku == code)).first()\n    if not product:\n        return jsonify({'error': 'Product not found.'}), 404\n    inventory = Inventory.query.filter_by(product_id=product.id).first()\n    return jsonify({\n        'id': product.id,\n        'name': product.name,\n        'price': product.sale_price,\n        'available': inventory.quantity if inventory else 0,\n        'barcode': product.barcode or '',\n        'sku': product.sku or ''\n    })\n\n@app.route('/cashier/checkout', methods=['POST'])\n@login_required\n@cashier_required\ndef cashier_checkout():\n    form = SaleForm()\n    customers = Customer.query.all()\n    form.customer_id.choices = [(0, '-- Select Customer --')] + [(c.id, c.name) for c in customers]\n    if form.validate_on_submit():\n        try:\n            create_sale_from_form(form, request.form, current_user.id)\n        except SaleProcessingError as exc:\n            db.session.rollback()\n            flash(str(exc), 'danger')\n            return redirect(url_for('cashier_pos'))\n        db.session.commit()\n        flash('Sale recorded through cashier.', 'success')\n        return redirect(url_for('cashier_pos'))\n    flash('Please complete the form correctly.', 'danger')\n    return redirect(url_for('cashier_pos'))\n\n@app.route('/cashier/logs')\n@login_required\n@admin_required\ndef cashier_logs():\n    cash_sales = Sale.query.options(joinedload(Sale.cashier)).filter(Sale.cashier_id.isnot(None)).order_by(Sale.created_at.desc()).all()\n    return render_template('cashier/logs.html', sales=cash_sales)\n\n"""
text = text[:start] + block + text[end:]
path.write_text(text, encoding='utf-8')
